# Generated by Django 4.1.5 on 2023-01-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Задача', max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Время создания задачи')),
                ('completed', models.BooleanField(default=False, help_text='Отметка о выполнении')),
                ('completed_time', models.DateTimeField(default=None, help_text='Время завершения задачи', null=True)),
            ],
        ),
    ]
