# Generated by Django 4.1.5 on 2023-01-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='completed_time',
            field=models.DateTimeField(blank=True, default=None, help_text='Время завершения задачи', null=True),
        ),
    ]
